language: ruby
before_install:
  - gem update --system 2.1.11
  - gem --version
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
gemfile:
  - gemfiles/standalone.gemfile
  - gemfiles/binding_of_caller.gemfile
  - gemfiles/rake.gemfile
  - gemfiles/rack.gemfile
  - gemfiles/sinatra.gemfile
  - gemfiles/rails2.3.gemfile
  - gemfiles/rails.gemfile
  - gemfiles/rails3.0.gemfile
  - gemfiles/rails3.1.gemfile
  - gemfiles/rails3.2.gemfile
