language: ruby
cache: bundler
before_install: gem install bundler
gemfile:
  - gemfiles/standalone.gemfile
  - gemfiles/binding_of_caller.gemfile
  - gemfiles/delayed_job.gemfile
  - gemfiles/rails.gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - jruby-19mode
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
  exclude:
    - rvm: jruby-19mode
      gemfile: gemfiles/binding_of_caller.gemfile
env:
  global:
    secure: DwQI6QHuRRaMoKvE9rnXmw3U1KLKH6Y1ZTXCcDN34Zkq7QG5KPt195zvL6XPbsefvd2fOHq4es5D6jxgLlEdKB7njhWX8XNMgb/eprz6zTxSAS/ep31zYHEJ3krWSPM6a7fXJOjdYIzXhVl7I0NRDZGy/Sf6LgHIBMpaGVKGc34=
