language: ruby
cache: bundler
before_install: gem install bundler
sudo: false
gemfile:
  - gemfiles/standalone.gemfile
  - gemfiles/binding_of_caller.gemfile
  - gemfiles/delayed_job.gemfile
  - gemfiles/rack.gemfile
  - gemfiles/sinatra.gemfile
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails.gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - jruby-19mode
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
  exclude:
    - rvm: jruby-19mode
      gemfile: gemfiles/binding_of_caller.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails.gemfile
env:
  global:
    secure: DwQI6QHuRRaMoKvE9rnXmw3U1KLKH6Y1ZTXCcDN34Zkq7QG5KPt195zvL6XPbsefvd2fOHq4es5D6jxgLlEdKB7njhWX8XNMgb/eprz6zTxSAS/ep31zYHEJ3krWSPM6a7fXJOjdYIzXhVl7I0NRDZGy/Sf6LgHIBMpaGVKGc34=
