language: ruby
cache: bundler
gemfile:
  - gemfiles/standalone.gemfile
  - gemfiles/binding_of_caller.gemfile
  - gemfiles/delayed_job.gemfile
  - gemfiles/rails2.3.gemfile
  - gemfiles/rails.gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-19mode
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
  exclude:
    - rvm: jruby-19mode
      gemfile: gemfiles/binding_of_caller.gemfile
